version: '3.5'
services:
  db:
    build: postgresql
    image: postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - lbrry_ntwrk
  pgadmin:
    build: pgadmin
    image: pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - "db"
    networks:
      - lbrry_ntwrk
  library:
    build: library_test
    image: library_test:1.0.0
    ports:
      - "80:8080"
    depends_on:
      - "pgadmin"
    restart: always
    networks:
      - lbrry_ntwrk
  swagger-ui:
    build: swagger-ui
    image: library_swagger-ui:1.0.0
    ports:
      - "81:8081"
    networks:
      - lbrry_ntwrk

networks:
  lbrry_ntwrk:
    name: lbrry_ntwrk
